language: python
python:
    - "2.7"
install:
    - cd arpeggio
    - python setup.py install
    - cd ..
    - cd domm
    - python setup.py install
    - cd ..
    - pip install enum34
script:
    - make check

